[package]
name = "finite-state-machines"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
youchoose = "0.1.0"
serde_json = "1.0.70"